---
distFolder: dist
setup:
- name: Setup project
  action: actions/setup-node@v1
  properties:
    node-version: v14.x
prepare:
  name: Prepare project environment
  command: npm ci
build:
  name: Build project
  command: npm run build
  environment:
    CI: true
    SITE_URL: ${{ steps.project.outputs.site-url }}
    URL_WEB: https://ionos.space
    URL_GITHUB: https://github.com/ionos-deploy-now/documentation/tree/main
